const ANALYTICS_EVENT_NAMES = [
  'page_view',
  'session_ping',
  'client_error',
  'cta_click',
  'pricing_view',
  'pricing_cta_click',
  'premium_preview_viewed',
  'premium_preview_interacted',
  'premium_checkout_clicked',
  'premium_checkout_created',
  'premium_checkout_failed',
  'premium_checkout_returned',
  'premium_subscription_activated',
  'premium_onboarding_started',
  'login_started',
  'login_success',
  'auth_completed',
  'login_error',
  'signup_started',
  'signup_completed',
  'signup_error',
  'post_signup_landing',
  'post_signup_landing_cta_clicked',
  'auth_mode_switch',
  'profile_completed',
  'student_material_processing_ready',
  'student_material_study_opened',
  'pdf_gate_viewed',
  'pdf_gate_cta_clicked',
  'materia_tab_viewed',
  'materia_resumen_opened',
  'materia_resource_opened',
  'materia_simulator_cta_clicked',
  'preguntero_shared',
  'simulator_ready',
  'simulator_started',
  'simulator_progress_checkpoint',
  'simulator_needs_feedback',
  'simulator_resumed',
  'simulator_finished',
  'simulator_abandoned',
  'simulator_login_gate_viewed',
  'simulator_login_gate_cta_clicked',
  'simulator_result_shared',
  'simulator_rating',
  'demo_checkpoint_reached',
  'premium_cta_clicked',
  'premium_gate_viewed',
  'limit_reached_explanations',
  'limit_reached_errores_review',
  'limit_reached_calendar_exam',
  'limit_reached_material_upload',
  'explanation_history_viewed',
  'reminder_created',
  'reminder_dismissed',
] as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENT_NAMES)[number];

const ANALYTICS_EVENT_NAME_SET = new Set<string>(ANALYTICS_EVENT_NAMES);

export function isAllowedAnalyticsEventName(value: string): value is AnalyticsEventName {
  return ANALYTICS_EVENT_NAME_SET.has(value);
}
